version: 1.0.{build}
image: Visual Studio 2022
configuration:
- Release
install:
- cmd: >-
    nuget restore && cd ./gramdictru && npm install
build:
  publish_aspnet_core: true
  verbosity: minimal
environment:
  NODE_OPTIONS: --openssl-legacy-provider
  